// Define action types
export const REQUEST_LOC_DATA = 'REQUEST_LOC_DATA';
export const RECEIVE_LOC_DATA = 'RECEIVE_LOC_DATA';
export const REQUEST_WEATHER_DATA = 'REQUEST_WEATHER_DATA';
export const RECEIVE_WEATHER_DATA = 'RECEIVE_WEATHER_DATA';
export const REQUEST_FORECAST_DATA = 'REQUEST_FORECAST_DATA';
export const RECEIVE_FORECAST_DATA = 'RECEIVE_FORECAST_DATA';
export const RESET_STATE = 'RESET_STATE';